import Link from "next/link";

const activities=[["শিক্ষা ও দক্ষতা","শিক্ষার সুযোগ, সচেতনতা এবং দক্ষতা উন্নয়নের উদ্যোগ।"],["মানবিক সহায়তা","প্রয়োজনের সময় অসহায় ও সুবিধাবঞ্চিত মানুষের পাশে থাকা।"],["সামাজিক উন্নয়ন","স্থানীয় মানুষের অংশগ্রহণে টেকসই সামাজিক উদ্যোগ।"]];

export default function HomePage() {
  return <>
    <section className="relative overflow-hidden bg-zinc-950"><div className="absolute inset-0 bg-[url('/village.jpg')] bg-cover bg-center opacity-35"/><div className="absolute inset-0 bg-gradient-to-r from-zinc-950 via-zinc-950/85 to-emerald-950/50"/><div className="relative mx-auto grid min-h-[600px] max-w-7xl items-center px-4 py-20 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:px-8"><div className="max-w-3xl text-white"><span className="inline-flex rounded-full border border-white/15 bg-white/10 px-3 py-1 text-sm font-medium text-emerald-100">মানুষ • মানবতা • ভবিষ্যৎ</span><h1 className="mt-6 text-4xl font-bold leading-tight sm:text-5xl lg:text-6xl">একতাবদ্ধ উদ্যোগে<br/><span className="text-emerald-300">সুন্দর ভবিষ্যৎ</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-zinc-200 sm:text-lg">ফিউচার হোপ অ্যান্ড হিউম্যানিটি ফাউন্ডেশন মানুষের জীবনমান উন্নয়ন, শিক্ষা, মানবিক সহায়তা ও সামাজিক কল্যাণে কাজ করার একটি সম্মিলিত উদ্যোগ।</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/activities" className="rounded-xl bg-emerald-500 px-5 py-3 text-center font-semibold text-white hover:bg-emerald-400">আমাদের কার্যক্রম</Link><Link href="/contact" className="rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-center font-semibold text-white hover:bg-white/15">যোগাযোগ করুন</Link></div></div><div className="hidden lg:block"><div className="ml-auto max-w-sm rounded-3xl border border-white/10 bg-white/10 p-7 backdrop-blur"><p className="text-sm font-semibold text-emerald-200">আমাদের অঙ্গীকার</p><p className="mt-4 text-2xl font-bold leading-10 text-white">“একজন মানুষের পাশে দাঁড়ানো থেকেই একটি পরিবর্তনের শুরু।”</p></div></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold text-emerald-700">আমাদের লক্ষ্য</p><h2 className="mt-2 text-3xl font-bold sm:text-4xl">কাজের মাধ্যমে ইতিবাচক পরিবর্তন</h2><p className="mt-4 leading-8 text-zinc-500">স্থানীয় বাস্তবতা ও মানুষের প্রয়োজনকে গুরুত্ব দিয়ে ছোট, কার্যকর এবং মানবিক উদ্যোগ গড়ে তোলাই আমাদের লক্ষ্য।</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{activities.map(([title,text],i)=><article key={title} className="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:shadow-md"><span className="inline-flex rounded-xl bg-emerald-50 px-3 py-2 text-xs font-bold text-emerald-700">০{i+1}</span><h3 className="mt-5 text-xl font-bold">{title}</h3><p className="mt-3 leading-7 text-zinc-500">{text}</p></article>)}</div></section>
    <section className="bg-emerald-950"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-16 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8"><div className="text-white"><h2 className="text-3xl font-bold">আপনিও এই উদ্যোগের অংশ হতে পারেন</h2><p className="mt-2 text-emerald-100">আমাদের সম্পর্কে আরও জানুন অথবা সরাসরি যোগাযোগ করুন।</p></div><Link href="/about" className="rounded-xl bg-white px-5 py-3 text-center font-semibold text-emerald-900 hover:bg-emerald-50">আমাদের সম্পর্কে</Link></div></section>
  </>;
}
